
ALTER TABLE usuarios_perfis
    ADD CONSTRAINT pk_usuarios_perfis PRIMARY KEY (usuario_id, perfil_id);

ALTER TABLE respostas
    DROP FOREIGN KEY FK_RESPOSTAS_ON_TOPICO;

ALTER TABLE respostas
    ADD CONSTRAINT FK_RESPOSTAS_ON_TOPICO
    FOREIGN KEY (topico_id) REFERENCES topicos (topico_id)
    ON DELETE CASCADE;

ALTER TABLE respostas
    DROP FOREIGN KEY FK_RESPOSTAS_ON_USUARIO;

ALTER TABLE respostas
    ADD CONSTRAINT FK_RESPOSTAS_ON_USUARIO
    FOREIGN KEY (usuario_id) REFERENCES usuarios (usuario_id)
    ON DELETE RESTRICT;

ALTER TABLE respostas
    DROP FOREIGN KEY FK_RESPOSTAS_ON_USUARIO;

ALTER TABLE respostas
    ADD CONSTRAINT FK_RESPOSTAS_ON_USUARIO
    FOREIGN KEY (usuario_id) REFERENCES usuarios (usuario_id)
    ON DELETE CASCADE;

ALTER TABLE topicos
    DROP FOREIGN KEY FK_TOPICOS_ON_USUARIO;

ALTER TABLE topicos
    ADD CONSTRAINT FK_TOPICOS_ON_USUARIO
    FOREIGN KEY (usuario_id) REFERENCES usuarios (usuario_id)
    ON DELETE CASCADE;

